# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20171014_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='select',
            field=models.CharField(blank=True, db_column='select', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(blank=True, choices=[('Audio', (('vinyl', 'Vinyl'), ('cd', 'CD'))), ('Video', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('unknown', 'Unknown'), ('', 'Nothing to add')], default=None, max_length=50),
            preserve_default=False,
        ),
    ]
