# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20171014_2129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='select',
            new_name='sel',
        ),
    ]
