# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20171014_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sel',
            field=models.CharField(blank=True, db_column='select-db', max_length=50, null=True),
        ),
    ]
