# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20171014_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='sel',
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(blank=True, choices=[('Audio', (('vinyl', 'Vinyl'), ('cd', 'CD'))), ('Video', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('unknown', 'Unknown'), ('', 'Nothing to add')], max_length=50),
        ),
    ]
