# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20171019_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img_profile',
            field=models.ImageField(default='profile.jpg', null=True, upload_to='user'),
        ),
    ]
