# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_auto_20171020_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='liked_posts',
            field=models.ManyToManyField(null=True, to='post.Post', verbose_name='좋아요 포스트 목록'),
        ),
    ]
