# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 14:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_auto_20171023_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('relation_type', models.CharField(choices=[('FOLLOW', 'Following relation'), ('BLOCK', 'Blocking relation')], default='FOLLOW', max_length=10)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myrelations_with_stars', to=settings.AUTH_USER_MODEL)),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myrelations_with_followers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='stars',
            field=models.ManyToManyField(null=True, related_name='followers', through='member.Relation', to=settings.AUTH_USER_MODEL),
        ),
    ]
