# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 15:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_auto_20171023_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img_profile',
            field=models.ImageField(default='default/profile.jpg', null=True, upload_to='user', verbose_name='프로필 이미지'),
        ),
        migrations.AlterField(
            model_name='user',
            name='liked_posts',
            field=models.ManyToManyField(to='post.Post', verbose_name='좋아요 포스트 목록'),
        ),
        migrations.AlterField(
            model_name='user',
            name='stars',
            field=models.ManyToManyField(related_name='followers', through='member.Relation', to=settings.AUTH_USER_MODEL),
        ),
    ]
