# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_auto_20171024_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('D', 'Django Login'), ('F', 'Facebook Login')], default='D', max_length=2),
            preserve_default=False,
        ),
    ]
