# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 00:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='relation_type',
            field=models.CharField(choices=[('F', 'Following relation'), ('B', 'Blocking relation')], default='FOLLOW', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=50, verbose_name='닉네임'),
        ),
        migrations.AlterField(
            model_name='user',
            name='stars',
            field=models.ManyToManyField(related_name='followers', through='member.Relation', to=settings.AUTH_USER_MODEL, verbose_name='follow'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('D', 'Django Login'), ('F', 'Facebook Login')], max_length=1),
        ),
    ]
