# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_auto_20171026_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='introduction',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
